name: build webrix project
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - name: install npm dependencies
      run: npm install
    - name: npm build
      run: npm run build:prod
      continue-on-error: true
    # - name: Publish to Registry
    #   uses: elgohr/Publish-Docker-Github-Action@v5
    #   with:
    #     name: scribesecurity/webrix:latest
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    - name: Generate SBOM
      uses: scribe-security/action-bom@master
      with:
        target: 'scribesecurity/webrix:latest'
        format: cyclonedx-json
        verbose: 2
        scribe-enable: 'true'
        product-key: 'scribesecurity/webrix'
        scribe-client-id: ${{ secrets.CLIENT_ID }}
        scribe-client-secret: ${{ secrets.CLIENT_SECRET }}
    - name: check envs
      # env:
        # GITHUB_CONTEXT: ${{ toJson(github) }}
        # WF: ${{ toJson(github.event.workflow) }}
      run: echo "${{ github.event.workflow }}"
        
