name: verify packages through build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install jq
      run:  | 
        sudo apt-get install jq
        jq

    - name: install valint
      run: | 
        curl -sSfL https://get.scribesecurity.com/install.sh  | sh -s -- -t valint
        /home/runner/.scribe/bin/valint --help

#     - name: install npm dependencies
#       run: npm install

#     - name: generate current dependency list
#       id: valint_json
#       uses: scribe-security/action-bom@master
#       with:
#         type: dir
#         target: .
#         output-file: build-dependencies-sbom.json

    - name: create dependencies comp
      run: |
        /home/runner/.scribe/bin/valint diff webrix-dependencies-sbom.json webrix-dependencies-sbom.json -vv --integrity modified -O modified.json --paths node_modules:node_modules
        cat modified.json
        cat modified.json | jq .synopsis
        
    - name: evaluate comp
      run: |
        result=$(cat modified.json | jq ".synopsis.modified")
        echo $result
        if [ "$result" -ne "0" ]
        then 
          echo "Package integrity error."
          exit(1)
        else
          echo "Package integrity validated successully."
        fi


    # - name: npm build
    #   run: npm run build:prod
    #   continue-on-error: true
    # - name: Publish to Registry
    #   uses: elgohr/Publish-Docker-Github-Action@v5
    #   with:
    #     name: scribesecurity/webrix:latest
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
