name: create sbom of dependecies as a baseline

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install npm
        run: npm install

      - name: Generate cyclonedx json SBOM
        id: valint_json
        uses: scribe-security/action-bom@master
        with:
          type: dir
          target: .
          output-file: webrix_dependencies_sbom.json

      - uses: actions/upload-artifact@v2
        with:
          name: scribe-sbom
          path: ${{ steps.valint_json.outputs.OUTPUT_PATH }}

          
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add webrix-dependencies-sbom.json
          git commit -a -m "uploaded dependencies sbom"
         
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
